// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float3> vertex;
int numVertex;


[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numVertex)
        return;
    // TODO: insert actual code here!
    vertex[id.x] = float3(0,0,0);
}
